export const images = {
  Logo: require('./Logo.png'),
  LogoGradient: require('./LogoGradient.png'),
  profile: require('./profile.png'),
  location: require('./location.png'),
  deposite: require('./deposite.png'),
  starbugimage: require('./starbugimage.png'),
  verification_image: require('./verification_image.png'),
  Ach: require('./ach.png'),
  coinbase: require('./coinbase.png'),
  stripe: require('./stripe.png'),
  deposit: require('./deposit.png'),
  processing: require('./processing.png'),
  error: require('./error.png'),
  success: require('./success.png'),
  documentdownload: require('./documentdownload.png'),
  downarror: require('./downarror.png'),
  to: require('./to.png'),
  profileImage: require('./profileView.png'),
  paypal: require('./paypal.png'),
  phone: require('./phone.png'),
  bank: require('./bank.png'),
  personalcard: require('./personalcard.png'),
  arrow: require('./arrow.png'),
  arrow2: require('./arrow2.png'),
  refresh: require('./refresh-page-option.png')
}