# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
itc_team_id = CredentialsManager::AppfileConfig.try_fetch_value(:itc_team_id)


base_name = 'JetSet'

type="appstore"
filename = "#{base_name}.xcodeproj"
workspace_name = "#{base_name}.xcworkspace"
porfile_env = "sigh_#{identifier}_#{type}_profile-path"


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :certs do
    match(app_identifier: identifier, type: type, readonly: true)
  end
  lane :beta do
    # increment_build_number(xcodeproj: filename)
    certs
    # update_code_signing_settings(
    #   use_automatic_signing: false,
    #   path: filename,
    #   code_sign_identity: 'iPhone Distribution'
    # )
    # sigh
    update_project_provisioning(
      xcodeproj: filename,
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution",
      profile: ENV["sigh_#{identifier}_#{type}_profile-path"]
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: filename,
      code_sign_identity: 'iPhone Distribution'
    )
    # build_ios_app
    build_app(
      workspace: workspace_name, 
      scheme: base_name,
      configuration: 'Release',
      # clean: true,
      export_method: "app-store",
    )
    upload_to_testflight
  end
end
